### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by anachronic** [tapankarnik/Kpop-Idol-Face-Classifier#1]
First of all, I'd like to congratulate a wonderful project like this.

I'm wondering if I can use some of this work for a school project that I have? Just want to make it sure that it's possible. If it's not, all cool.

Thanks!

**Comment by tapankarnik** [comment]
Sure, go ahead. As long as you give a star :)

**Comment by anachronic** [comment]
Already did! Thanks, I'm gonna close
